### ISSUE TITLE
[RANK] Koi x Shin Ai Kanojo

### ISSUE THREAD

**Issue by anhnsnd** [ngoduyanh/nrs-impl-kt#256]
Type: Visual Novel

Koi x Shin Ai Kanojo: https://vndb.org/v17516

**Comment by anhnsnd** [comment]
`Visual(VisualKind.VisualNovel, 1.0, *)` inc 👀

**Comment by ngoduyanh** [comment]
time to spam aei/nei boys

**Comment by ngoduyanh** [comment]
![image](https://user-images.githubusercontent.com/43819821/204213576-afe75e17-7066-4b79-a2d2-fa7f84c9402b.png)
blatant overbuff lmfao

**Comment by ngoduyanh** [comment]
BRO STOP
![image](https://user-images.githubusercontent.com/43819821/205674203-470e6083-e272-4c0b-8f18-011efb2c9ead.png)

**Comment by anhnsnd** [comment]
no :trollface:

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by ngoduyanh** [comment]
worst mistake of my life

**Comment by ngoduyanh** [comment]
> hifumi >>> sena

kys

**Comment by btmxh** [comment]
mommy pls save me
