### ISSUE TITLE
[RANK] Post-modern romance anime

### ISSUE THREAD

**Issue by ngoduyanh** [ngoduyanh/nrs-impl-kt#326]
Type: Anime

Nakitai Watashi wa Neko wo Kaburu: https://myanimelist.net/anime/41168
Zutto Mae kara Suki deshita. Kokuhaku Jikkou Iinkai: https://myanimelist.net/anime/31245
Suki ni Naru Sono Shunkan wo. Kokuhaku Jikkou Iinkai: https://myanimelist.net/anime/33036
Itsudatte Bokura no Koi wa 10 cm Datta.: https://myanimelist.net/anime/36220

**Comment by ngoduyanh** [comment]
koi kakeru shin ai kanojo and its consequences :skull: :skull: :skull: :skull: :skull: :skull:

**Comment by btmxh** [comment]
> Zutto Mae kara Suki deshita. Kokuhaku Jikkou Iinkai: https://myanimelist.net/anime/31245
> Suki ni Naru Sono Shunkan wo. Kokuhaku Jikkou Iinkai: https://myanimelist.net/anime/33036
> Itsudatte Bokura no Koi wa 10 cm Datta.: https://myanimelist.net/anime/36220

they didn't know that this shit gonna give birth to the longest waifuslop in history skull skull

**Comment by btmxh** [comment]
> koi kakeru shin ai kanojo and its consequences 💀 💀 💀 💀 💀 💀

they didn't know that this shit gonna give birth to the most overrated albumslop and novelslop in history skull skull
